### ISSUE TITLE
Electron app on Ubuntu 16 only displays the light blue color as the background

### ISSUE THREAD

**Issue by lightswarm124** [bigearth/bitbox-electron#12]
No other data, just a nice soothing blue background

**Comment by cgcardona** [comment]
Thanks for the bug report. I haven't run it on anything other than MacOS.

Can you open the dev tools (it's option+cmnd+i on MacOS) and see what the error/stack trace is?

It's built w/ electron so you should see the same dev tools as Chrome browser. Here's a screenshot from my machine.

<img width="1286" alt="screen shot 2018-04-02 at 6 47 23 pm" src="https://user-images.githubusercontent.com/260614/38224861-cd08fb1c-36a6-11e8-9649-3bacb8077671.png">

**Comment by cgcardona** [comment]
Did you install it w/ the mac installer or did you clone the repo and run it that way? Def want to solve the issue. Thanks again for reporting it. 🎩

**Comment by lightswarm124** [comment]
I cloned the repo and ran it that way. I'll check out where the error shows up

**Comment by cgcardona** [comment]
Thanks. Appreciated.

**Comment by cgcardona** [comment]
Also I wanted to mention that you can still play around w/ `bitbox-cli` independent of the GUI.

It gives you access to `bitbox new`, `bitbox scaffold` and `bitbox console` so you can try out the commands.

```
> npm install bitbox-cli --global
> bitbox new --title myApp
> cd myApp
> bitbox console
> BITBOX.Mnemonic.generateMnemonic(256)
// giggle tonight desk into wait tired tennis physical cruel turtle grow labor mystery promote decrease need lend bunker sea immune renew cable coach fantasy
```

Here's the actual script of how I got `bitbox-cli` working earlier on a digital ocean ubuntu instance

```
> apt-get update --yes 
> apt-get upgrade --yes 
> sudo reboot
> apt-get install python2.7 --yes 
> ln -s /usr/bin/python2.7 /usr/bin/python 
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
> source ~/.bashrc
> nvm install 9.4.0
> npm install bitbox-cli --global
> bitbox new --title myApp
> cd myApp/
> bitbox console
> BITBOX.Mnemonic.generateMnemonic(256)
// giggle tonight desk into wait tired tennis physical cruel turtle grow labor mystery promote decrease need lend bunker sea immune renew cable coach fantasy
```

I set up a slack channel if you'd like to come there and chat. bitboxearth.slack.com. Send me your email and I can send you an invite if you're interested.

**Comment by lightswarm124** [comment]
It's lightswarm@gmail.com

I think the issue is that in the index.html file, it's requiring a "bundle.js" that is missing from the repository. I resolved it after building the webpack. I initially thought it was like a dev environment

**Comment by cgcardona** [comment]
Ok cool. So the GUI working? If so I'll close this issue. Thx.
