### ISSUE TITLE
error in bitbox new if .bitboxrc does not exist

### ISSUE THREAD

**Issue by dfoderick** [bigearth/bitbox-electron#9]
I'm not ready to do pull requests so I will describe the issue.

In line 61 of index.js there is an error if config file does not exist. Obviously config is not defined. Work around is to create empty .bitboxrc file with contents {}

C:\Users\Dave\AppData\Roaming\npm\node_modules\bitbox-cli\index.js:61
      } else if(config.new && config.new.environment) {
                       ^

TypeError: Cannot read property 'new' of undefined
    at ReadFileContext.fs.readFile [as callback] (C:\Users\Dave\AppData\Roaming\npm\node_modules\bitbox-cli\index.js:61:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)

**Comment by cgcardona** [comment]
Nice catch! I think [this change to `bitbox-cli`](https://github.com/bigearth/bitbox-cli/commit/7ee7f7c6be342acdb91ee6358063d46d2d1267b7) fixes the issue. Basically I just needed to code more defensively and check that those objects exist before trying to access one of their properties.

Please let me know if you continue to see the problem. Thanks again!
